### PR TITLE
IPC scream change

### PR DESCRIPTION
**Pull request by Spacemanspark**
Changes the IPC scream noise thingy.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Christ, no.

👎 from me, it sounds awful.

**Comment by Spacemanspark** [comment]
Since you're a nerd and blocked me on the Discord and I have to say this here, if people don't comment on this by tomorrow with their opinions, I'll be closing this.

**Comment by FlattestGuitar** [comment]
👌 🙆‍♂️ 🙆

**Comment by Spacemanspark** [comment]
:middle_finger: :^)

**Comment by FlattestGuitar** [comment]
Seems like there isn't enough support.

**Pull request closed without merging**
